version: 2.1
jobs:
  build:
    working_directory: ~/addons

    docker:
    # Primary container image where all commands run
      - image: antilhuecom/odoo-base
        environment:
          DB_HOST: 127.0.0.1
          DATABASE: odoo
          USER: odoo
          ODOO_ENVIROMENT: CI
    # Service container image available at `host: localhost`
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: odoo
          POSTGRES_DB: odoo
          POSTGRES_PASSWORD: odoo

    steps:
      - checkout
      - run:
          name: Install dependences
          command: |
            apt-get update
            apt-get install wget
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            pip3 install -r requirements.txt
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: init db
          command: 
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Install odoo
          command: |
            odoo -d odoo --db_host $DB_HOST -r $USER --stop-after-init
      - run:
          name: Install modules and Run test
          command: 
            odoo -d odoo --db_host $DB_HOST -r $USER --addons-path=$ADDONS_PATH -u  $MODULE_TEST --test-enable --log-level=test --stop-after-init
          environment:
            ADDONS_PATH: "./addons"
            MODULE_TEST: "modulo_libros,modulo_prueba,sales_package_summary,website_sale_algolia,website_sale_category_menu,auth_signup_approval,website_quote_attach_document,website_sale_quote,delivery_cost_customs,l10n_cl_dpa,aws_monitoring"
      - store_test_results:
          path: test-results

  deploy:
    working_directory: ~/addons
    docker:
      - image: antilhuecom/odoo-base
        environment:
          DB_HOST: 127.0.0.1
          DATABASE: odoo
          USER: odoo
          ODOO_ENVIROMENT: CI
          
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: odoo
          POSTGRES_DB: odoo
          POSTGRES_PASSWORD: odoo
    steps:
      - run:
          name: Deploy to production
          command: |
            odoo -d odoo --db_host $DB_HOST -r $USER --addons-path=$ADDONS_PATH -i  $MODULE_TEST --stop-after-init
          environment:
            ADDONS_PATH: "./addons"
            MODULE_TEST: "modulo_libros,modulo_prueba,sales_package_summary,website_sale_algolia,website_sale_category_menu,auth_signup_approval,website_quote_attach_document,website_sale_quote,delivery_cost_customs,l10n_cl_dpa,aws_monitoring"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
            
            
    
